version: '2'
services:
    influxdb:
        image: influxdb
        ports:
            - "8086:8086"
            - "8083:8083"
            - "2003:2003"
        environment:
            - INFLUXDB_GRAPHITE_ENABLED=true
        restart: always
    
    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"
        links:
            - "influxdb:influxdb"
        restart: always